- name: Install MySQL
  ansible.builtin.yum:
    name: mysql-server
    state: present

- name: Start MySQL service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true

- name: Create application database
  community.mysql.mysql_db:
    name: appdb
    state: present

- name: Create application user
  community.mysql.mysql_user:
    name: appuser
    password: "NJL123456789"
    priv: "appdb.*:ALL"
    host: "%"
    state: present
